### ISSUE TITLE
12 - Slices

### ISSUE THREAD

**Issue by vovs03** [vovs03/python_ex#22]
# 12 - Slices

- Подстроки `val[0:5]` | `val[:5]` | `val[18:]` 
- Шаг извлечения
- Отрицательные индексы `val[-5:]`

![photo_2023-03-05 11 29 01](https://user-images.githubusercontent.com/21124057/222950131-e30b3674-b709-4284-b3b9-b200b05d1c2a.jpeg)

---

## ДОМАШНЕЕ ЗАДАНИЕ

Имеется строка `str = "Slice"`. На выходе должно быть `Cil`.
**Необходимо**
- создать слайс, 
- перевернуть его 
- и `методом Х` создать заглавную букву.

@Sergei089 прикрепи код/ решение в комментарии ниже, здесь **НА ГИТХАБЕ**

**Comment by Sergei089** [comment]
```Python
str = "Slice"

x = str[3:-5:-1]
print(x.title())

```

**Comment by vovs03** [comment]
<img width="636" alt="Screenshot 2023-03-07 at 12 56 39" src="https://user-images.githubusercontent.com/21124057/224229556-5f657703-3496-40e6-8bcf-9f8d5b44ca5d.png">
