### ISSUE TITLE
💩 ПИНОК под ЗАД № 278 

### ISSUE THREAD

**Issue by vovs03** [vovs03/python_ex#30]
# 💩 ПИНОК под ЗАД № 278 

Такое в программировании происходит часто. 
Если вы @Sergei089 не знаете синтаксис, 
то **можно все равно** 
`пробовать комбинировать различные подходы`, 
и есть вероятность, что они заработают.

## Задание
<img width="398" alt="Screenshot 2023-03-21 at 20 21 21" src="https://user-images.githubusercontent.com/21124057/226692131-28c2273d-2aa4-4d7f-852f-1e1ce6d89660.png">

`Что-то в этом коде можно улучшить? Если да, то что?`
Напиши ниже в комментарии свой ответ.

**Comment by Sergei089** [comment]
Надо убрать upper он лишний

**Comment by vovs03** [comment]
```
print(name.lower())
```
