### ISSUE TITLE
Задание 23.1 Каскадность

### ISSUE THREAD

**Issue by vovs03** [vovs03/python_ex#5]
# Задание 23.1

По теме 23 `CSS` > `Каскадность` https://ru.hexlet.io/courses/layout-designer-basics/lessons/css-cascade/theory_unit

Выполнить **Самостоятельная работа** 

- [ ] Прикрепить скриншот (Код + браузер[отображение])

**Comment by Sergei089** [comment]
![2023-01-26](https://user-images.githubusercontent.com/116675434/214773122-ff09da8c-b4a6-4e2c-bd39-1d009f8493e8.png)
